version: '3.8'

services:
  # MongoDB Database for development
  mongodb-dev:
    image: mongo:6-jammy
    container_name: portfolio-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_user
      MONGO_INITDB_ROOT_PASSWORD: dev_pass
      MONGO_INITDB_DATABASE: portfolio_dev
    ports:
      - "27018:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - portfolio-dev-network

  # MongoDB Express (Web UI for MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: portfolio-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev_pass
      ME_CONFIG_MONGODB_SERVER: mongodb-dev
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-dev
    networks:
      - portfolio-dev-network

volumes:
  mongodb_dev_data:

networks:
  portfolio-dev-network:
    driver: bridge