version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6-jammy
    container_name: portfolio-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: portfolio
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio-network

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGODB_URI: mongodb://admin:admin_password@mongodb:27017/portfolio?authSource=admin
      MONGODB_DATABASE: portfolio
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - portfolio-network

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network

volumes:
  mongodb_data:

networks:
  portfolio-network:
    driver: bridge